/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AdminCredentialPayload
 */
export interface AdminCredentialPayload {
    /**
     * 
     * @type {string}
     * @memberof AdminCredentialPayload
     */
    adminEmail: string;
    /**
     * 
     * @type {string}
     * @memberof AdminCredentialPayload
     */
    adminPassword: string;
}

export function AdminCredentialPayloadFromJSON(json: any): AdminCredentialPayload {
    return AdminCredentialPayloadFromJSONTyped(json, false);
}

export function AdminCredentialPayloadFromJSONTyped(json: any, _ignoreDiscriminator: boolean): AdminCredentialPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'adminEmail': json['adminEmail'],
        'adminPassword': json['adminPassword'],
    };
}

export function AdminCredentialPayloadToJSON(value?: AdminCredentialPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'adminEmail': value.adminEmail,
        'adminPassword': value.adminPassword,
    };
}


