/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum CalendarDefaultCalendarId {
    primary = 'primary',
    completed = 'completed'
}

export function CalendarDefaultCalendarIdFromJSON(json: any): CalendarDefaultCalendarId {
    return CalendarDefaultCalendarIdFromJSONTyped(json, false);
}

export function CalendarDefaultCalendarIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalendarDefaultCalendarId {
    return json as CalendarDefaultCalendarId;
}

export function CalendarDefaultCalendarIdToJSON(value?: CalendarDefaultCalendarId | null): any {
    return value as any;
}

