/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ContextInstance
 */
export interface ContextInstance {
    /**
     * $uuid
     * @type {string}
     * @memberof ContextInstance
     */
    uuid: string;
    /**
     * $databaseName
     * @type {string}
     * @memberof ContextInstance
     */
    databaseName: string;
}

export function ContextInstanceFromJSON(json: any): ContextInstance {
    return ContextInstanceFromJSONTyped(json, false);
}

export function ContextInstanceFromJSONTyped(json: any, _ignoreDiscriminator: boolean): ContextInstance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'databaseName': json['databaseName'],
    };
}

export function ContextInstanceToJSON(value?: ContextInstance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'databaseName': value.databaseName,
    };
}


