/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ContextPreferences
 */
export interface ContextPreferences {
    /**
     * $tz
     * @type {string}
     * @memberof ContextPreferences
     */
    tz: string;
    /**
     * $locale
     * @type {string}
     * @memberof ContextPreferences
     */
    locale: string;
    /**
     * $timeFormat
     * @type {string}
     * @memberof ContextPreferences
     */
    timeFormat: string;
    /**
     * $firstDayOfWeek
     * @type {string}
     * @memberof ContextPreferences
     */
    firstDayOfWeek: string;
}

export function ContextPreferencesFromJSON(json: any): ContextPreferences {
    return ContextPreferencesFromJSONTyped(json, false);
}

export function ContextPreferencesFromJSONTyped(json: any, _ignoreDiscriminator: boolean): ContextPreferences {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tz': json['tz'],
        'locale': json['locale'],
        'timeFormat': json['timeFormat'],
        'firstDayOfWeek': json['firstDayOfWeek'],
    };
}

export function ContextPreferencesToJSON(value?: ContextPreferences | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tz': value.tz,
        'locale': value.locale,
        'timeFormat': value.timeFormat,
        'firstDayOfWeek': value.firstDayOfWeek,
    };
}


