/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CredentialDto,
} from './';

/**
 * 
 * @export
 * @interface CredentialsResponse
 */
export interface CredentialsResponse {
    /**
     * 
     * @type {Array<CredentialDto>}
     * @memberof CredentialsResponse
     */
    credentials: Array<CredentialDto>;
}

export function CredentialsResponseFromJSON(json: any): CredentialsResponse {
    return CredentialsResponseFromJSONTyped(json, false);
}

export function CredentialsResponseFromJSONTyped(json: any, _ignoreDiscriminator: boolean): CredentialsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'credentials': Array&lt;CredentialDto&gt;FromJSON(json['credentials']),
    };
}

export function CredentialsResponseToJSON(value?: CredentialsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'credentials': Array&lt;CredentialDto&gt;ToJSON(value.credentials),
    };
}


