/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DateOrDateTime
 */
export interface DateOrDateTime {
    /**
     * 
     * @type {string}
     * @memberof DateOrDateTime
     */
    date?: string;
    /**
     * 
     * @type {Date}
     * @memberof DateOrDateTime
     */
    dateTime?: Date;
}

export function DateOrDateTimeFromJSON(json: any): DateOrDateTime {
    return DateOrDateTimeFromJSONTyped(json, false);
}

export function DateOrDateTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateOrDateTime {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : json['date'],
        'dateTime': !exists(json, 'dateTime') ? undefined : (new Date(json['dateTime'])),
    };
}

export function DateOrDateTimeToJSON(value?: DateOrDateTime | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date,
        'dateTime': value.dateTime === undefined ? undefined : (value.dateTime.toISOString()),
    };
}


