/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface DsfFinancialCenter
 */
export interface DsfFinancialCenter {
    /**
     * Id
     * @type {number}
     * @memberof DsfFinancialCenter
     */
    id: number;
    /**
     * French name
     * @type {string}
     * @memberof DsfFinancialCenter
     */
    nameFr: string;
    /**
     * English name
     * @type {string}
     * @memberof DsfFinancialCenter
     */
    nameEn: string;
    /**
     * SFL|DFSI|DFSIN|VMD
     * @type {string}
     * @memberof DsfFinancialCenter
     */
    network: string;
    /**
     * Code
     * @type {string}
     * @memberof DsfFinancialCenter
     */
    code?: string | null;
    /**
     * Organization Unique Id
     * @type {string}
     * @memberof DsfFinancialCenter
     */
    organizationUuid?: string | null;
    /**
     * Code
     * @type {number}
     * @memberof DsfFinancialCenter
     */
    databaseCount: number;
}

export function DsfFinancialCenterFromJSON(json: any): DsfFinancialCenter {
    return DsfFinancialCenterFromJSONTyped(json, false);
}

export function DsfFinancialCenterFromJSONTyped(json: any, _ignoreDiscriminator: boolean): DsfFinancialCenter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nameFr': json['nameFr'],
        'nameEn': json['nameEn'],
        'network': json['network'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'organizationUuid': !exists(json, 'organizationUuid') ? undefined : json['organizationUuid'],
        'databaseCount': json['databaseCount'],
    };
}

export function DsfFinancialCenterToJSON(value?: DsfFinancialCenter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'nameFr': value.nameFr,
        'nameEn': value.nameEn,
        'network': value.network,
        'code': value.code,
        'organizationUuid': value.organizationUuid,
        'databaseCount': value.databaseCount,
    };
}


