/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface DsfFinancialCenterPayload
 */
export interface DsfFinancialCenterPayload {
    /**
     * French name
     * @type {string}
     * @memberof DsfFinancialCenterPayload
     */
    nameFr: string;
    /**
     * English name
     * @type {string}
     * @memberof DsfFinancialCenterPayload
     */
    nameEn: string;
    /**
     * SFL|DFSI|DFSIN|VMD
     * @type {string}
     * @memberof DsfFinancialCenterPayload
     */
    network: string;
    /**
     * Code
     * @type {string}
     * @memberof DsfFinancialCenterPayload
     */
    code?: string;
}

export function DsfFinancialCenterPayloadFromJSON(json: any): DsfFinancialCenterPayload {
    return DsfFinancialCenterPayloadFromJSONTyped(json, false);
}

export function DsfFinancialCenterPayloadFromJSONTyped(json: any, _ignoreDiscriminator: boolean): DsfFinancialCenterPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nameFr': json['nameFr'],
        'nameEn': json['nameEn'],
        'network': json['network'],
        'code': !exists(json, 'code') ? undefined : json['code'],
    };
}

export function DsfFinancialCenterPayloadToJSON(value?: DsfFinancialCenterPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nameFr': value.nameFr,
        'nameEn': value.nameEn,
        'network': value.network,
        'code': value.code,
    };
}


