/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EventsVisibilityType {
    NORMAL = 'NORMAL',
    PRIVATE = 'PRIVATE'
}

export function EventsVisibilityTypeFromJSON(json: any): EventsVisibilityType {
    return EventsVisibilityTypeFromJSONTyped(json, false);
}

export function EventsVisibilityTypeFromJSONTyped(json: any, _ignoreDiscriminator: boolean): EventsVisibilityType {
    return json as EventsVisibilityType;
}

export function EventsVisibilityTypeToJSON(value?: EventsVisibilityType | null): any {
    return value as any;
}

