/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface EventsTransferToCompletedResponse
 */
export interface EventsTransferToCompletedResponse {
    /**
     * Unique numerical identifier of the updated event.
     * @type {string}
     * @memberof EventsTransferToCompletedResponse
     */
    id: string;
}

export function EventsTransferToCompletedResponseFromJSON(json: any): EventsTransferToCompletedResponse {
    return EventsTransferToCompletedResponseFromJSONTyped(json, false);
}

export function EventsTransferToCompletedResponseFromJSONTyped(json: any, _ignoreDiscriminator: boolean): EventsTransferToCompletedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function EventsTransferToCompletedResponseToJSON(value?: EventsTransferToCompletedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


