/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EventsEvent,
    EventsEventFromJSON,
    EventsEventFromJSONTyped,
    EventsEventToJSON,
} from './';

/**
 * 
 * @export
 * @interface EventsGetEventInstancesResponse
 */
export interface EventsGetEventInstancesResponse {
    /**
     * Opaque token used to get the next page of the result. Omitted if no more results.
     * @type {string}
     * @memberof EventsGetEventInstancesResponse
     */
    nextPageToken?: string;
    /**
     * 
     * @type {Array<EventsEvent>}
     * @memberof EventsGetEventInstancesResponse
     */
    items: Array<EventsEvent>;
}

export function EventsGetEventInstancesResponseFromJSON(json: any): EventsGetEventInstancesResponse {
    return EventsGetEventInstancesResponseFromJSONTyped(json, false);
}

export function EventsGetEventInstancesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsGetEventInstancesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nextPageToken': !exists(json, 'nextPageToken') ? undefined : json['nextPageToken'],
        'items': ((json['items'] as Array<any>).map(EventsEventFromJSON)),
    };
}

export function EventsGetEventInstancesResponseToJSON(value?: EventsGetEventInstancesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nextPageToken': value.nextPageToken,
        'items': ((value.items as Array<any>).map(EventsEventToJSON)),
    };
}


