/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventsCreateEventResponse
 */
export interface EventsCreateEventResponse {
    /**
     * Unique numerical identifier of the created event.
     * @type {string}
     * @memberof EventsCreateEventResponse
     */
    id: string;
}

export function EventsCreateEventResponseFromJSON(json: any): EventsCreateEventResponse {
    return EventsCreateEventResponseFromJSONTyped(json, false);
}

export function EventsCreateEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsCreateEventResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function EventsCreateEventResponseToJSON(value?: EventsCreateEventResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


