/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    GatewaysAccessesAccess,
    GatewaysAccessesAccessFromJSON,
    GatewaysAccessesAccessToJSON,
} from './';

/**
 * 
 * @export
 * @interface GatewaysAccessesListGatewayAccessesResponse
 */
export interface GatewaysAccessesListGatewayAccessesResponse {
    /**
     * 
     * @type {Array<GatewaysAccessesAccess>}
     * @memberof GatewaysAccessesListGatewayAccessesResponse
     */
    items: Array<GatewaysAccessesAccess>;
}

export function GatewaysAccessesListGatewayAccessesResponseFromJSON(json: any): GatewaysAccessesListGatewayAccessesResponse {
    return GatewaysAccessesListGatewayAccessesResponseFromJSONTyped(json, false);
}

export function GatewaysAccessesListGatewayAccessesResponseFromJSONTyped(json: any, _ignoreDiscriminator: boolean): GatewaysAccessesListGatewayAccessesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(GatewaysAccessesAccessFromJSON)),
    };
}

export function GatewaysAccessesListGatewayAccessesResponseToJSON(value?: GatewaysAccessesListGatewayAccessesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(GatewaysAccessesAccessToJSON)),
    };
}


