/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface GatewaysAccessesEquisoftAnalyzeAccessAllOf
 */
export interface GatewaysAccessesEquisoftAnalyzeAccessAllOf {
    /**
     * 
     * @type {string}
     * @memberof GatewaysAccessesEquisoftAnalyzeAccessAllOf
     */
    clientKey: string;
    /**
     * 
     * @type {string}
     * @memberof GatewaysAccessesEquisoftAnalyzeAccessAllOf
     */
    version: GatewaysAccessesEquisoftAnalyzeAccessAllOfVersionEnum;
}

export function GatewaysAccessesEquisoftAnalyzeAccessAllOfFromJSON(json: any): GatewaysAccessesEquisoftAnalyzeAccessAllOf {
    return GatewaysAccessesEquisoftAnalyzeAccessAllOfFromJSONTyped(json, false);
}

export function GatewaysAccessesEquisoftAnalyzeAccessAllOfFromJSONTyped(json: any, _ignoreDiscriminator: boolean): GatewaysAccessesEquisoftAnalyzeAccessAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientKey': json['clientKey'],
        'version': json['version'],
    };
}

export function GatewaysAccessesEquisoftAnalyzeAccessAllOfToJSON(value?: GatewaysAccessesEquisoftAnalyzeAccessAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clientKey': value.clientKey,
        'version': value.version,
    };
}

/**
* @export
* @enum {string}
*/
export enum GatewaysAccessesEquisoftAnalyzeAccessAllOfVersionEnum {
    NATIVE = 'NATIVE',
    LEGACY = 'LEGACY'
}


