/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';

/**
 * 
 * @export
 * @interface GatewaysCredentialsWithSsn
 */
export interface GatewaysCredentialsWithSsn {
    /**
     * 
     * @type {string}
     * @memberof GatewaysCredentialsWithSsn
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof GatewaysCredentialsWithSsn
     */
    password: string;
    /**
     * 
     * @type {boolean}
     * @memberof GatewaysCredentialsWithSsn
     */
    isADealerCode?: boolean;
    /**
     * The list will contain formatted SSNs, i.e. "123 456 789"
     * @type {Array<string>}
     * @memberof GatewaysCredentialsWithSsn
     */
    ssnList?: Array<string>;
}

export function GatewaysCredentialsWithSsnFromJSON(json: any): GatewaysCredentialsWithSsn {
    return GatewaysCredentialsWithSsnFromJSONTyped(json, false);
}

export function GatewaysCredentialsWithSsnFromJSONTyped(json: any, _ignoreDiscriminator: boolean): GatewaysCredentialsWithSsn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'isADealerCode': !exists(json, 'isADealerCode') ? undefined : json['isADealerCode'],
        'ssnList': !exists(json, 'ssnList') ? undefined : json['ssnList'],
    };
}

export function GatewaysCredentialsWithSsnToJSON(value?: GatewaysCredentialsWithSsn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
        'isADealerCode': value.isADealerCode,
        'ssnList': value.ssnList,
    };
}


