/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    GatewaysCredentials,
    GatewaysCredentialsFromJSON,
    GatewaysCredentialsToJSON,
} from './';

/**
 * 
 * @export
 * @interface GatewaysListCredentialsResponse
 */
export interface GatewaysListCredentialsResponse {
    /**
     * 
     * @type {Array<GatewaysCredentials>}
     * @memberof GatewaysListCredentialsResponse
     */
    credentials: Array<GatewaysCredentials>;
}

export function GatewaysListCredentialsResponseFromJSON(json: any): GatewaysListCredentialsResponse {
    return GatewaysListCredentialsResponseFromJSONTyped(json, false);
}

export function GatewaysListCredentialsResponseFromJSONTyped(json: any, _ignoreDiscriminator: boolean): GatewaysListCredentialsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'credentials': ((json['credentials'] as Array<any>).map(GatewaysCredentialsFromJSON)),
    };
}

export function GatewaysListCredentialsResponseToJSON(value?: GatewaysListCredentialsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'credentials': ((value.credentials as Array<any>).map(GatewaysCredentialsToJSON)),
    };
}


