/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    GatewaysAccessesAccess,
    GatewaysAccessesAccessFromJSONTyped,
    GatewaysAccessesAccessToJSON,
} from './';

/**
 * 
 * @export
 * @interface GatewaysAccessesEquisoftAnalyzeAccess
 */
export interface GatewaysAccessesEquisoftAnalyzeAccess extends GatewaysAccessesAccess {
    /**
     * 
     * @type {string}
     * @memberof GatewaysAccessesEquisoftAnalyzeAccess
     */
    clientKey: string;
    /**
     * 
     * @type {string}
     * @memberof GatewaysAccessesEquisoftAnalyzeAccess
     */
    version: GatewaysAccessesEquisoftAnalyzeAccessVersionEnum;
}

export function GatewaysAccessesEquisoftAnalyzeAccessFromJSON(json: any): GatewaysAccessesEquisoftAnalyzeAccess {
    return GatewaysAccessesEquisoftAnalyzeAccessFromJSONTyped(json, false);
}

export function GatewaysAccessesEquisoftAnalyzeAccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewaysAccessesEquisoftAnalyzeAccess {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...GatewaysAccessesAccessFromJSONTyped(json, ignoreDiscriminator),
        'clientKey': json['clientKey'],
        'version': json['version'],
    };
}

export function GatewaysAccessesEquisoftAnalyzeAccessToJSON(value?: GatewaysAccessesEquisoftAnalyzeAccess | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...GatewaysAccessesAccessToJSON(value),
        'clientKey': value.clientKey,
        'version': value.version,
    };
}

/**
* @export
* @enum {string}
*/
export enum GatewaysAccessesEquisoftAnalyzeAccessVersionEnum {
    NATIVE = 'NATIVE',
    LEGACY = 'LEGACY'
}


