/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * List of gateway types
 * @export
 * @enum {string}
 */
export enum GatewaysGatewayType {
    EQUISOFT_ANALYZE = 'EQUISOFT_ANALYZE'
}

export function GatewaysGatewayTypeFromJSON(json: any): GatewaysGatewayType {
    return GatewaysGatewayTypeFromJSONTyped(json, false);
}

export function GatewaysGatewayTypeFromJSONTyped(json: any, _ignoreDiscriminator: boolean): GatewaysGatewayType {
    return json as GatewaysGatewayType;
}

export function GatewaysGatewayTypeToJSON(value?: GatewaysGatewayType | null): any {
    return value as any;
}

