/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    GatewaysAccessesUser,
} from './';

import {
     GatewaysAccessesEquisoftAnalyzeAccessFromJSONTyped
} from './';

/**
 * 
 * @export
 * @interface GatewaysAccessesAccess
 */
export interface GatewaysAccessesAccess {
    /**
     * 
     * @type {number}
     * @memberof GatewaysAccessesAccess
     */
    id: number;
    /**
     * 
     * @type {Array<GatewaysAccessesUser>}
     * @memberof GatewaysAccessesAccess
     */
    users: Array<GatewaysAccessesUser>;
}

export function GatewaysAccessesAccessFromJSON(json: any): GatewaysAccessesAccess {
    return GatewaysAccessesAccessFromJSONTyped(json, false);
}

export function GatewaysAccessesAccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewaysAccessesAccess {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['type'] === 'EQUISOFT_ANALYZE') {
            return GatewaysAccessesEquisoftAnalyzeAccessFromJSONTyped(json, true);
        }
    }
    return {
        
        'id': json['id'],
        'users': Array&lt;GatewaysAccessesUser&gt;FromJSON(json['users']),
    };
}

export function GatewaysAccessesAccessToJSON(value?: GatewaysAccessesAccess | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'users': Array&lt;GatewaysAccessesUser&gt;ToJSON(value.users),
    };
}


