/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface GatewaysAccessesPatchEquisoftAnalyzeAccessPayload
 */
export interface GatewaysAccessesPatchEquisoftAnalyzeAccessPayload {
    /**
     * 
     * @type {string}
     * @memberof GatewaysAccessesPatchEquisoftAnalyzeAccessPayload
     */
    clientKey?: string;
}

export function GatewaysAccessesPatchEquisoftAnalyzeAccessPayloadFromJSON(json: any): GatewaysAccessesPatchEquisoftAnalyzeAccessPayload {
    return GatewaysAccessesPatchEquisoftAnalyzeAccessPayloadFromJSONTyped(json, false);
}

export function GatewaysAccessesPatchEquisoftAnalyzeAccessPayloadFromJSONTyped(json: any, _ignoreDiscriminator: boolean): GatewaysAccessesPatchEquisoftAnalyzeAccessPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientKey': !exists(json, 'clientKey') ? undefined : json['clientKey'],
    };
}

export function GatewaysAccessesPatchEquisoftAnalyzeAccessPayloadToJSON(value?: GatewaysAccessesPatchEquisoftAnalyzeAccessPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clientKey': value.clientKey,
    };
}


