/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GatewaysAccessesUser,
    GatewaysAccessesUserFromJSON,
    GatewaysAccessesUserFromJSONTyped,
    GatewaysAccessesUserToJSON,
} from './';

import {
     GatewaysAccessesEquisoftAnalyzeAccessFromJSONTyped
} from './';

/**
 * 
 * @export
 * @interface GatewaysAccessesAccess
 */
export interface GatewaysAccessesAccess {
    /**
     * 
     * @type {string}
     * @memberof GatewaysAccessesAccess
     */
    type?: GatewaysAccessesAccessTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof GatewaysAccessesAccess
     */
    id: number;
    /**
     * 
     * @type {Array<GatewaysAccessesUser>}
     * @memberof GatewaysAccessesAccess
     */
    users: Array<GatewaysAccessesUser>;
}

export function GatewaysAccessesAccessFromJSON(json: any): GatewaysAccessesAccess {
    return GatewaysAccessesAccessFromJSONTyped(json, false);
}

export function GatewaysAccessesAccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewaysAccessesAccess {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['type'] === 'EQUISOFT_ANALYZE') {
            return GatewaysAccessesEquisoftAnalyzeAccessFromJSONTyped(json, true);
        }
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'id': json['id'],
        'users': ((json['users'] as Array<any>).map(GatewaysAccessesUserFromJSON)),
    };
}

export function GatewaysAccessesAccessToJSON(value?: GatewaysAccessesAccess | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'users': ((value.users as Array<any>).map(GatewaysAccessesUserToJSON)),
    };
}

/**
* @export
* @enum {string}
*/
export enum GatewaysAccessesAccessTypeEnum {
    EQUISOFT_ANALYZE = 'EQUISOFT_ANALYZE'
}


