/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * List of gateway name that are fixed.
 * @export
 * @enum {string}
 */
export enum GatewaysGatewayName {
    EQUISOFT_ANALYZE = 'EQUISOFT_ANALYZE'
}

export function GatewaysGatewayNameFromJSON(json: any): GatewaysGatewayName {
    return GatewaysGatewayNameFromJSONTyped(json, false);
}

export function GatewaysGatewayNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewaysGatewayName {
    return json as GatewaysGatewayName;
}

export function GatewaysGatewayNameToJSON(value?: GatewaysGatewayName | null): any {
    return value as any;
}

