/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface GatewaysAccessesCreateEquisoftAnalyzeAccessPayload
 */
export interface GatewaysAccessesCreateEquisoftAnalyzeAccessPayload {
    /**
     * Uuid of the user attached to the gateway access
     * @type {string}
     * @memberof GatewaysAccessesCreateEquisoftAnalyzeAccessPayload
     */
    userUuid: string;
    /**
     * 
     * @type {string}
     * @memberof GatewaysAccessesCreateEquisoftAnalyzeAccessPayload
     */
    clientKey: string;
}

export function GatewaysAccessesCreateEquisoftAnalyzeAccessPayloadFromJSON(json: any): GatewaysAccessesCreateEquisoftAnalyzeAccessPayload {
    return GatewaysAccessesCreateEquisoftAnalyzeAccessPayloadFromJSONTyped(json, false);
}

export function GatewaysAccessesCreateEquisoftAnalyzeAccessPayloadFromJSONTyped(json: any, _ignoreDiscriminator: boolean): GatewaysAccessesCreateEquisoftAnalyzeAccessPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userUuid': json['userUuid'],
        'clientKey': json['clientKey'],
    };
}

export function GatewaysAccessesCreateEquisoftAnalyzeAccessPayloadToJSON(value?: GatewaysAccessesCreateEquisoftAnalyzeAccessPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userUuid': value.userUuid,
        'clientKey': value.clientKey,
    };
}


