/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GatewaysAccessesCreateAccessResponse
 */
export interface GatewaysAccessesCreateAccessResponse {
    /**
     * Unique numerical identifier of the created access.
     * @type {number}
     * @memberof GatewaysAccessesCreateAccessResponse
     */
    id: number;
}

export function GatewaysAccessesCreateAccessResponseFromJSON(json: any): GatewaysAccessesCreateAccessResponse {
    return GatewaysAccessesCreateAccessResponseFromJSONTyped(json, false);
}

export function GatewaysAccessesCreateAccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewaysAccessesCreateAccessResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function GatewaysAccessesCreateAccessResponseToJSON(value?: GatewaysAccessesCreateAccessResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


