/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface HandlersOauth2AssetbookAssetBookTokenPostBody
 */
export interface HandlersOauth2AssetbookAssetBookTokenPostBody {
    /**
     * 
     * @type {string}
     * @memberof HandlersOauth2AssetbookAssetBookTokenPostBody
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersOauth2AssetbookAssetBookTokenPostBody
     */
    refreshToken: string;
}

export function HandlersOauth2AssetbookAssetBookTokenPostBodyFromJSON(json: any): HandlersOauth2AssetbookAssetBookTokenPostBody {
    return HandlersOauth2AssetbookAssetBookTokenPostBodyFromJSONTyped(json, false);
}

export function HandlersOauth2AssetbookAssetBookTokenPostBodyFromJSONTyped(json: any, _ignoreDiscriminator: boolean): HandlersOauth2AssetbookAssetBookTokenPostBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['Username'],
        'refreshToken': json['RefreshToken'],
    };
}

export function HandlersOauth2AssetbookAssetBookTokenPostBodyToJSON(value?: HandlersOauth2AssetbookAssetBookTokenPostBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Username': value.username,
        'RefreshToken': value.refreshToken,
    };
}


