/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface InternalNotesLegacyNote
 */
export interface InternalNotesLegacyNote {
    /**
     * Legacy note content.
     * @type {string}
     * @memberof InternalNotesLegacyNote
     */
    content: string;
}

export function InternalNotesLegacyNoteFromJSON(json: any): InternalNotesLegacyNote {
    return InternalNotesLegacyNoteFromJSONTyped(json, false);
}

export function InternalNotesLegacyNoteFromJSONTyped(json: any, _ignoreDiscriminator: boolean): InternalNotesLegacyNote {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function InternalNotesLegacyNoteToJSON(value?: InternalNotesLegacyNote | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
    };
}


