/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum InternalNotesHistoryType {
    full = 'full',
    latestOnly = 'latestOnly'
}

export function InternalNotesHistoryTypeFromJSON(json: any): InternalNotesHistoryType {
    return InternalNotesHistoryTypeFromJSONTyped(json, false);
}

export function InternalNotesHistoryTypeFromJSONTyped(json: any, _ignoreDiscriminator: boolean): InternalNotesHistoryType {
    return json as InternalNotesHistoryType;
}

export function InternalNotesHistoryTypeToJSON(value?: InternalNotesHistoryType | null): any {
    return value as any;
}

