/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum InternalNotesNoteRevisionType {
    CREATE = 'CREATE',
    MODIFY = 'MODIFY',
    ARCHIVE = 'ARCHIVE',
    RESTORE = 'RESTORE'
}

export function InternalNotesNoteRevisionTypeFromJSON(json: any): InternalNotesNoteRevisionType {
    return InternalNotesNoteRevisionTypeFromJSONTyped(json, false);
}

export function InternalNotesNoteRevisionTypeFromJSONTyped(json: any, _ignoreDiscriminator: boolean): InternalNotesNoteRevisionType {
    return json as InternalNotesNoteRevisionType;
}

export function InternalNotesNoteRevisionTypeToJSON(value?: InternalNotesNoteRevisionType | null): any {
    return value as any;
}

