/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface InternalNotesNoteRevision
 */
export interface InternalNotesNoteRevision {
    /**
     * Unique numerical identifier.
     * @type {number}
     * @memberof InternalNotesNoteRevision
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InternalNotesNoteRevision
     */
    type?: string;
    /**
     * Note content
     * @type {string}
     * @memberof InternalNotesNoteRevision
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof InternalNotesNoteRevision
     */
    createdAt: Date;
}

export function InternalNotesNoteRevisionFromJSON(json: any): InternalNotesNoteRevision {
    return InternalNotesNoteRevisionFromJSONTyped(json, false);
}

export function InternalNotesNoteRevisionFromJSONTyped(json: any, _ignoreDiscriminator: boolean): InternalNotesNoteRevision {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'content': json['content'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function InternalNotesNoteRevisionToJSON(value?: InternalNotesNoteRevision | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'content': value.content,
        'createdAt': (value.createdAt.toISOString()),
    };
}


