/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    InternalNotesLegacyNote,
    InternalNotesLegacyNoteFromJSON,
    InternalNotesLegacyNoteToJSON,
    InternalNotesNote,
} from './';

/**
 * 
 * @export
 * @interface InternalNotesNoteList
 */
export interface InternalNotesNoteList {
    /**
     * 
     * @type {Array<InternalNotesNote>}
     * @memberof InternalNotesNoteList
     */
    notes: Array<InternalNotesNote>;
    /**
     * 
     * @type {InternalNotesLegacyNote}
     * @memberof InternalNotesNoteList
     */
    legacyNote?: InternalNotesLegacyNote;
}

export function InternalNotesNoteListFromJSON(json: any): InternalNotesNoteList {
    return InternalNotesNoteListFromJSONTyped(json, false);
}

export function InternalNotesNoteListFromJSONTyped(json: any, _ignoreDiscriminator: boolean): InternalNotesNoteList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'notes': Array&lt;InternalNotesNote&gt;FromJSON(json['notes']),
        'legacyNote': !exists(json, 'legacyNote') ? undefined : InternalNotesLegacyNoteFromJSON(json['legacyNote']),
    };
}

export function InternalNotesNoteListToJSON(value?: InternalNotesNoteList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'notes': Array&lt;InternalNotesNote&gt;ToJSON(value.notes),
        'legacyNote': InternalNotesLegacyNoteToJSON(value.legacyNote),
    };
}


