/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalNotesAuthor
 */
export interface InternalNotesAuthor {
    /**
     * Unique numerical identifier.
     * @type {string}
     * @memberof InternalNotesAuthor
     */
    id?: string;
    /**
     * Globally unique identifier.
     * @type {string}
     * @memberof InternalNotesAuthor
     */
    uuid: string;
    /**
     * Author name
     * @type {string}
     * @memberof InternalNotesAuthor
     */
    displayName: string;
}

export function InternalNotesAuthorFromJSON(json: any): InternalNotesAuthor {
    return InternalNotesAuthorFromJSONTyped(json, false);
}

export function InternalNotesAuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalNotesAuthor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'uuid': json['uuid'],
        'displayName': json['displayName'],
    };
}

export function InternalNotesAuthorToJSON(value?: InternalNotesAuthor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'uuid': value.uuid,
        'displayName': value.displayName,
    };
}


