/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface LaserAppLaserAppAnywhereError
 */
export interface LaserAppLaserAppAnywhereError {
    /**
     * $message;
     * @type {string}
     * @memberof LaserAppLaserAppAnywhereError
     */
    message: string;
}

export function LaserAppLaserAppAnywhereErrorFromJSON(json: any): LaserAppLaserAppAnywhereError {
    return LaserAppLaserAppAnywhereErrorFromJSONTyped(json, false);
}

export function LaserAppLaserAppAnywhereErrorFromJSONTyped(json: any, _ignoreDiscriminator: boolean): LaserAppLaserAppAnywhereError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function LaserAppLaserAppAnywhereErrorToJSON(value?: LaserAppLaserAppAnywhereError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}


