/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LegacyDocumentBase64FilePayload,
    LegacyDocumentBase64FilePayloadFromJSON,
    LegacyDocumentBase64FilePayloadFromJSONTyped,
    LegacyDocumentBase64FilePayloadToJSON,
} from './';

/**
 * Wrapper for Legacy payload argument
 * @export
 * @interface LegacyDocumentUploadDocumentFileRequest
 */
export interface LegacyDocumentUploadDocumentFileRequest {
    /**
     * 
     * @type {LegacyDocumentBase64FilePayload}
     * @memberof LegacyDocumentUploadDocumentFileRequest
     */
    payload: LegacyDocumentBase64FilePayload;
}

export function LegacyDocumentUploadDocumentFileRequestFromJSON(json: any): LegacyDocumentUploadDocumentFileRequest {
    return LegacyDocumentUploadDocumentFileRequestFromJSONTyped(json, false);
}

export function LegacyDocumentUploadDocumentFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegacyDocumentUploadDocumentFileRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'payload': LegacyDocumentBase64FilePayloadFromJSON(json['payload']),
    };
}

export function LegacyDocumentUploadDocumentFileRequestToJSON(value?: LegacyDocumentUploadDocumentFileRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'payload': LegacyDocumentBase64FilePayloadToJSON(value.payload),
    };
}


