/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LegacyProvisioningOrganizationItem,
    LegacyProvisioningOrganizationItemFromJSON,
    LegacyProvisioningOrganizationItemFromJSONTyped,
    LegacyProvisioningOrganizationItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface LegacyProvisioningGetOrganizationListResponseAllOf
 */
export interface LegacyProvisioningGetOrganizationListResponseAllOf {
    /**
     * List of organization
     * @type {Array<LegacyProvisioningOrganizationItem>}
     * @memberof LegacyProvisioningGetOrganizationListResponseAllOf
     */
    organizations: Array<LegacyProvisioningOrganizationItem>;
}

export function LegacyProvisioningGetOrganizationListResponseAllOfFromJSON(json: any): LegacyProvisioningGetOrganizationListResponseAllOf {
    return LegacyProvisioningGetOrganizationListResponseAllOfFromJSONTyped(json, false);
}

export function LegacyProvisioningGetOrganizationListResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegacyProvisioningGetOrganizationListResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'organizations': ((json['organizations'] as Array<any>).map(LegacyProvisioningOrganizationItemFromJSON)),
    };
}

export function LegacyProvisioningGetOrganizationListResponseAllOfToJSON(value?: LegacyProvisioningGetOrganizationListResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'organizations': ((value.organizations as Array<any>).map(LegacyProvisioningOrganizationItemToJSON)),
    };
}


