/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LegacyDocumentDocumentListItem,
    LegacyDocumentDocumentListItemFromJSON,
    LegacyDocumentDocumentListItemFromJSONTyped,
    LegacyDocumentDocumentListItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface LegacyDocumentGetListResponseAllOf
 */
export interface LegacyDocumentGetListResponseAllOf {
    /**
     * Array of documents
     * @type {Array<LegacyDocumentDocumentListItem>}
     * @memberof LegacyDocumentGetListResponseAllOf
     */
    documents: Array<LegacyDocumentDocumentListItem>;
}

export function LegacyDocumentGetListResponseAllOfFromJSON(json: any): LegacyDocumentGetListResponseAllOf {
    return LegacyDocumentGetListResponseAllOfFromJSONTyped(json, false);
}

export function LegacyDocumentGetListResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegacyDocumentGetListResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documents': ((json['documents'] as Array<any>).map(LegacyDocumentDocumentListItemFromJSON)),
    };
}

export function LegacyDocumentGetListResponseAllOfToJSON(value?: LegacyDocumentGetListResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'documents': ((value.documents as Array<any>).map(LegacyDocumentDocumentListItemToJSON)),
    };
}


