/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LegacyDocumentDocument,
    LegacyDocumentDocumentFromJSON,
    LegacyDocumentDocumentFromJSONTyped,
    LegacyDocumentDocumentToJSON,
    LegacyDocumentGetResponseAllOf,
    LegacyDocumentGetResponseAllOfFromJSON,
    LegacyDocumentGetResponseAllOfFromJSONTyped,
    LegacyDocumentGetResponseAllOfToJSON,
    LegacyResponse,
    LegacyResponseFromJSON,
    LegacyResponseFromJSONTyped,
    LegacyResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface LegacyDocumentGetResponse
 */
export interface LegacyDocumentGetResponse {
    /**
     * Status of the request that has been made. Can be 'ok' or 'fail'
     * @type {string}
     * @memberof LegacyDocumentGetResponse
     */
    stat?: string;
    /**
     * If the request has failed, this element will contain the error code related to the problem encountered.
     * @type {string}
     * @memberof LegacyDocumentGetResponse
     */
    errorCode?: string;
    /**
     * If the request has failed, this element will contain the error message related to the problem encountered.
     * @type {string}
     * @memberof LegacyDocumentGetResponse
     */
    errorMsg?: string;
    /**
     * Array of documents
     * @type {Array<LegacyDocumentDocument>}
     * @memberof LegacyDocumentGetResponse
     */
    documents: Array<LegacyDocumentDocument>;
}

export function LegacyDocumentGetResponseFromJSON(json: any): LegacyDocumentGetResponse {
    return LegacyDocumentGetResponseFromJSONTyped(json, false);
}

export function LegacyDocumentGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegacyDocumentGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stat': !exists(json, 'stat') ? undefined : json['stat'],
        'errorCode': !exists(json, 'error_code') ? undefined : json['error_code'],
        'errorMsg': !exists(json, 'error_msg') ? undefined : json['error_msg'],
        'documents': ((json['documents'] as Array<any>).map(LegacyDocumentDocumentFromJSON)),
    };
}

export function LegacyDocumentGetResponseToJSON(value?: LegacyDocumentGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stat': value.stat,
        'error_code': value.errorCode,
        'error_msg': value.errorMsg,
        'documents': ((value.documents as Array<any>).map(LegacyDocumentDocumentToJSON)),
    };
}


