/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';

/**
 * 
 * @export
 * @interface LegacyContactContactPayloadItem
 */
export interface LegacyContactContactPayloadItem {
    /**
     * Unique id
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    id?: string;
    /**
     * Contact UUID
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    uuid?: string;
    /**
     * type of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    typeContact?: string;
    /**
     * type INDIVIDUAL OR ORGANIZATION
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    indOrg?: string;
    /**
     * display name of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    displayName?: string;
    /**
     * first name of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    firstName?: string;
    /**
     * nickname of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    nickname?: string;
    /**
     * middle name of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    middleName?: string;
    /**
     * last name of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    lastName?: string;
    /**
     * first line of corporation name (Organization)
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    corporationName?: string;
    /**
     * second line of corporation name (Organization)
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    corporationNameLine2?: string;
    /**
     * rank of the contact. (Industrial Alliance only)
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    rank?: string;
    /**
     * external key
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    externalKey?: string;
    /**
     * External key type
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    externalKeyType?: string;
    /**
     * Gender of the contact. Either MALE or FEMALE
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    gender?: string;
    /**
     * sin of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    sin?: string;
    /**
     * birthdate of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    birthdate?: string;
    /**
     * Smoker status of the contact.
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    smoker?: string;
    /**
     * Smoker status since date.
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    smokerSince?: string;
    /**
     * phone number of the contact at home
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    phoneHome?: string;
    /**
     * second phone number of the contact at home
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    phoneHomeSecond?: string;
    /**
     * assistant phone number of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    phoneAssistant?: string;
    /**
     * office phone number of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    phoneOffice?: string;
    /**
     * second office phone number of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    phoneOfficeSecond?: string;
    /**
     * cell phone number of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    phoneCell?: string;
    /**
     * Pager phone number of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    phonePager?: string;
    /**
     * fax phone number of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    phoneFax?: string;
    /**
     * main email of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    mainEmail?: string;
    /**
     * personal email of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    emailPersonal?: string;
    /**
     * Web Site URL. This represent the main website for the contact.
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    webSite?: string;
    /**
     * business email of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    emailBusiness?: string;
    /**
     * business email of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    emailOther?: string;
    /**
     * notes of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    notes?: string;
    /**
     * peculiarity of the contact
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    peculiarity?: string;
    /**
     * End of the financial year (for organization)
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    endFinancialYear?: string;
    /**
     * Language
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    language?: string;
    /**
     * Active (boolean)
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    active?: string;
    /**
     * Publish (boolean)
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    publish?: string;
    /**
     * Title
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    title?: string;
    /**
     * Suffix
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    suffix?: string;
    /**
     * Civility
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    civility?: string;
    /**
     * Civility id
     * @type {number}
     * @memberof LegacyContactContactPayloadItem
     */
    civilityId?: number;
    /**
     * Person Addressed (Correspondance)
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    personAddressed?: string;
    /**
     * Organization name (Correspondance)
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    organizationLine1?: string;
    /**
     * Organization name - second line (Correspondance)
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    organizationLine2?: string;
    /**
     * Department (Correspondance)
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    department?: string;
    /**
     * Customer Number
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    customerNumber?: string;
    /**
     * Birth Place
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    birthPlace?: string;
    /**
     * Nationality
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    nationality?: string;
    /**
     * 
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    orgDateCreated?: string;
    /**
     * 
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    orgDateClosed?: string;
    /**
     * 
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    dateEndFinancialYear?: string;
    /**
     * 
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    orgIdNo?: string;
    /**
     * 
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    orgFedNo?: string;
    /**
     * 
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    orgProvNo?: string;
    /**
     * 
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    orgStateId?: string;
    /**
     * 
     * @type {string}
     * @memberof LegacyContactContactPayloadItem
     */
    orgEin?: string;
}

export function LegacyContactContactPayloadItemFromJSON(json: any): LegacyContactContactPayloadItem {
    return LegacyContactContactPayloadItemFromJSONTyped(json, false);
}

export function LegacyContactContactPayloadItemFromJSONTyped(json: any, _ignoreDiscriminator: boolean): LegacyContactContactPayloadItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'typeContact': !exists(json, 'typeContact') ? undefined : json['typeContact'],
        'indOrg': !exists(json, 'indOrg') ? undefined : json['indOrg'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'nickname': !exists(json, 'nickname') ? undefined : json['nickname'],
        'middleName': !exists(json, 'middleName') ? undefined : json['middleName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'corporationName': !exists(json, 'corporationName') ? undefined : json['corporationName'],
        'corporationNameLine2': !exists(json, 'corporationNameLine2') ? undefined : json['corporationNameLine2'],
        'rank': !exists(json, 'rank') ? undefined : json['rank'],
        'externalKey': !exists(json, 'externalKey') ? undefined : json['externalKey'],
        'externalKeyType': !exists(json, 'externalKeyType') ? undefined : json['externalKeyType'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'sin': !exists(json, 'sin') ? undefined : json['sin'],
        'birthdate': !exists(json, 'birthdate') ? undefined : json['birthdate'],
        'smoker': !exists(json, 'smoker') ? undefined : json['smoker'],
        'smokerSince': !exists(json, 'smokerSince') ? undefined : json['smokerSince'],
        'phoneHome': !exists(json, 'phoneHome') ? undefined : json['phoneHome'],
        'phoneHomeSecond': !exists(json, 'phoneHomeSecond') ? undefined : json['phoneHomeSecond'],
        'phoneAssistant': !exists(json, 'phoneAssistant') ? undefined : json['phoneAssistant'],
        'phoneOffice': !exists(json, 'phoneOffice') ? undefined : json['phoneOffice'],
        'phoneOfficeSecond': !exists(json, 'phoneOfficeSecond') ? undefined : json['phoneOfficeSecond'],
        'phoneCell': !exists(json, 'phoneCell') ? undefined : json['phoneCell'],
        'phonePager': !exists(json, 'phonePager') ? undefined : json['phonePager'],
        'phoneFax': !exists(json, 'phoneFax') ? undefined : json['phoneFax'],
        'mainEmail': !exists(json, 'mainEmail') ? undefined : json['mainEmail'],
        'emailPersonal': !exists(json, 'emailPersonal') ? undefined : json['emailPersonal'],
        'webSite': !exists(json, 'webSite') ? undefined : json['webSite'],
        'emailBusiness': !exists(json, 'emailBusiness') ? undefined : json['emailBusiness'],
        'emailOther': !exists(json, 'emailOther') ? undefined : json['emailOther'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'peculiarity': !exists(json, 'peculiarity') ? undefined : json['peculiarity'],
        'endFinancialYear': !exists(json, 'endFinancialYear') ? undefined : json['endFinancialYear'],
        'language': !exists(json, 'language') ? undefined : json['language'],
        'active': !exists(json, 'active') ? undefined : json['active'],
        'publish': !exists(json, 'publish') ? undefined : json['publish'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'suffix': !exists(json, 'suffix') ? undefined : json['suffix'],
        'civility': !exists(json, 'civility') ? undefined : json['civility'],
        'civilityId': !exists(json, 'civilityId') ? undefined : json['civilityId'],
        'personAddressed': !exists(json, 'personAddressed') ? undefined : json['personAddressed'],
        'organizationLine1': !exists(json, 'organizationLine1') ? undefined : json['organizationLine1'],
        'organizationLine2': !exists(json, 'organizationLine2') ? undefined : json['organizationLine2'],
        'department': !exists(json, 'department') ? undefined : json['department'],
        'customerNumber': !exists(json, 'customerNumber') ? undefined : json['customerNumber'],
        'birthPlace': !exists(json, 'birthPlace') ? undefined : json['birthPlace'],
        'nationality': !exists(json, 'nationality') ? undefined : json['nationality'],
        'orgDateCreated': !exists(json, 'orgDateCreated') ? undefined : json['orgDateCreated'],
        'orgDateClosed': !exists(json, 'orgDateClosed') ? undefined : json['orgDateClosed'],
        'dateEndFinancialYear': !exists(json, 'dateEndFinancialYear') ? undefined : json['dateEndFinancialYear'],
        'orgIdNo': !exists(json, 'orgIdNo') ? undefined : json['orgIdNo'],
        'orgFedNo': !exists(json, 'orgFedNo') ? undefined : json['orgFedNo'],
        'orgProvNo': !exists(json, 'orgProvNo') ? undefined : json['orgProvNo'],
        'orgStateId': !exists(json, 'orgStateId') ? undefined : json['orgStateId'],
        'orgEin': !exists(json, 'orgEin') ? undefined : json['orgEin'],
    };
}

export function LegacyContactContactPayloadItemToJSON(value?: LegacyContactContactPayloadItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'uuid': value.uuid,
        'typeContact': value.typeContact,
        'indOrg': value.indOrg,
        'displayName': value.displayName,
        'firstName': value.firstName,
        'nickname': value.nickname,
        'middleName': value.middleName,
        'lastName': value.lastName,
        'corporationName': value.corporationName,
        'corporationNameLine2': value.corporationNameLine2,
        'rank': value.rank,
        'externalKey': value.externalKey,
        'externalKeyType': value.externalKeyType,
        'gender': value.gender,
        'sin': value.sin,
        'birthdate': value.birthdate,
        'smoker': value.smoker,
        'smokerSince': value.smokerSince,
        'phoneHome': value.phoneHome,
        'phoneHomeSecond': value.phoneHomeSecond,
        'phoneAssistant': value.phoneAssistant,
        'phoneOffice': value.phoneOffice,
        'phoneOfficeSecond': value.phoneOfficeSecond,
        'phoneCell': value.phoneCell,
        'phonePager': value.phonePager,
        'phoneFax': value.phoneFax,
        'mainEmail': value.mainEmail,
        'emailPersonal': value.emailPersonal,
        'webSite': value.webSite,
        'emailBusiness': value.emailBusiness,
        'emailOther': value.emailOther,
        'notes': value.notes,
        'peculiarity': value.peculiarity,
        'endFinancialYear': value.endFinancialYear,
        'language': value.language,
        'active': value.active,
        'publish': value.publish,
        'title': value.title,
        'suffix': value.suffix,
        'civility': value.civility,
        'civilityId': value.civilityId,
        'personAddressed': value.personAddressed,
        'organizationLine1': value.organizationLine1,
        'organizationLine2': value.organizationLine2,
        'department': value.department,
        'customerNumber': value.customerNumber,
        'birthPlace': value.birthPlace,
        'nationality': value.nationality,
        'orgDateCreated': value.orgDateCreated,
        'orgDateClosed': value.orgDateClosed,
        'dateEndFinancialYear': value.dateEndFinancialYear,
        'orgIdNo': value.orgIdNo,
        'orgFedNo': value.orgFedNo,
        'orgProvNo': value.orgProvNo,
        'orgStateId': value.orgStateId,
        'orgEin': value.orgEin,
    };
}


