/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LegacyProvisioningUserIdentifier
 */
export interface LegacyProvisioningUserIdentifier {
    /**
     * User unique identifier
     * @type {string}
     * @memberof LegacyProvisioningUserIdentifier
     */
    identifier?: string;
}

export function LegacyProvisioningUserIdentifierFromJSON(json: any): LegacyProvisioningUserIdentifier {
    return LegacyProvisioningUserIdentifierFromJSONTyped(json, false);
}

export function LegacyProvisioningUserIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegacyProvisioningUserIdentifier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
    };
}

export function LegacyProvisioningUserIdentifierToJSON(value?: LegacyProvisioningUserIdentifier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identifier': value.identifier,
    };
}


