/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';

/**
 * 
 * @export
 * @interface LegacyDocumentBase64FilePayloadItem
 */
export interface LegacyDocumentBase64FilePayloadItem {
    /**
     * id of the file
     * @type {string}
     * @memberof LegacyDocumentBase64FilePayloadItem
     */
    id?: string;
    /**
     * File name
     * @type {string}
     * @memberof LegacyDocumentBase64FilePayloadItem
     */
    fileName?: string;
    /**
     * Mime Type of the file
     * @type {string}
     * @memberof LegacyDocumentBase64FilePayloadItem
     */
    mimeType?: string;
    /**
     * Size of the file(in bytes)
     * @type {string}
     * @memberof LegacyDocumentBase64FilePayloadItem
     */
    sizeBytes?: string;
    /**
     * The file external key
     * @type {string}
     * @memberof LegacyDocumentBase64FilePayloadItem
     */
    externalKey?: string;
    /**
     * file data encoded in base 64
     * @type {string}
     * @memberof LegacyDocumentBase64FilePayloadItem
     */
    base64EncodedData?: string;
}

export function LegacyDocumentBase64FilePayloadItemFromJSON(json: any): LegacyDocumentBase64FilePayloadItem {
    return LegacyDocumentBase64FilePayloadItemFromJSONTyped(json, false);
}

export function LegacyDocumentBase64FilePayloadItemFromJSONTyped(json: any, _ignoreDiscriminator: boolean): LegacyDocumentBase64FilePayloadItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'fileName': !exists(json, 'fileName') ? undefined : json['fileName'],
        'mimeType': !exists(json, 'mimeType') ? undefined : json['mimeType'],
        'sizeBytes': !exists(json, 'sizeBytes') ? undefined : json['sizeBytes'],
        'externalKey': !exists(json, 'externalKey') ? undefined : json['externalKey'],
        'base64EncodedData': !exists(json, 'base64EncodedData') ? undefined : json['base64EncodedData'],
    };
}

export function LegacyDocumentBase64FilePayloadItemToJSON(value?: LegacyDocumentBase64FilePayloadItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'fileName': value.fileName,
        'mimeType': value.mimeType,
        'sizeBytes': value.sizeBytes,
        'externalKey': value.externalKey,
        'base64EncodedData': value.base64EncodedData,
    };
}


