/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LegacyDocumentDocumentPayloadItem,
    LegacyDocumentDocumentPayloadItemFromJSON,
    LegacyDocumentDocumentPayloadItemFromJSONTyped,
    LegacyDocumentDocumentPayloadItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface LegacyDocumentDocumentPayload
 */
export interface LegacyDocumentDocumentPayload {
    /**
     * List of document
     * @type {Array<LegacyDocumentDocumentPayloadItem>}
     * @memberof LegacyDocumentDocumentPayload
     */
    documents?: Array<LegacyDocumentDocumentPayloadItem>;
}

export function LegacyDocumentDocumentPayloadFromJSON(json: any): LegacyDocumentDocumentPayload {
    return LegacyDocumentDocumentPayloadFromJSONTyped(json, false);
}

export function LegacyDocumentDocumentPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegacyDocumentDocumentPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documents': !exists(json, 'documents') ? undefined : ((json['documents'] as Array<any>).map(LegacyDocumentDocumentPayloadItemFromJSON)),
    };
}

export function LegacyDocumentDocumentPayloadToJSON(value?: LegacyDocumentDocumentPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'documents': value.documents === undefined ? undefined : ((value.documents as Array<any>).map(LegacyDocumentDocumentPayloadItemToJSON)),
    };
}


