/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface LegacyDocumentGetListOptions
 */
export interface LegacyDocumentGetListOptions {
    /**
     * Fetch only document that are related to this contact id.
     * @type {number}
     * @memberof LegacyDocumentGetListOptions
     */
    contactId?: number;
    /**
     * Limit the result to $limit
     * @type {number}
     * @memberof LegacyDocumentGetListOptions
     */
    limit?: number;
    /**
     * Filter by system type.
     * @type {string}
     * @memberof LegacyDocumentGetListOptions
     */
    systemType?: string;
}

export function LegacyDocumentGetListOptionsFromJSON(json: any): LegacyDocumentGetListOptions {
    return LegacyDocumentGetListOptionsFromJSONTyped(json, false);
}

export function LegacyDocumentGetListOptionsFromJSONTyped(json: any, _ignoreDiscriminator: boolean): LegacyDocumentGetListOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contactId': !exists(json, 'contact_id') ? undefined : json['contact_id'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'systemType': !exists(json, 'system_type') ? undefined : json['system_type'],
    };
}

export function LegacyDocumentGetListOptionsToJSON(value?: LegacyDocumentGetListOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contact_id': value.contactId,
        'limit': value.limit,
        'system_type': value.systemType,
    };
}


