/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    LegacyContactContact,
    LegacyContactContactFromJSON,
    LegacyContactContactToJSON,
    LegacyDocumentFile,
    LegacyDocumentFileFromJSON,
    LegacyDocumentFileToJSON,
    LegacyUser,
    LegacyUserFromJSON,
    LegacyUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface LegacyDocumentDocument
 */
export interface LegacyDocumentDocument {
    /**
     * Files contained inside the document
     * @type {Array<LegacyDocumentFile>}
     * @memberof LegacyDocumentDocument
     */
    files?: Array<LegacyDocumentFile>;
    /**
     * List of linked contacts
     * @type {Array<LegacyContactContact>}
     * @memberof LegacyDocumentDocument
     */
    contacts?: Array<LegacyContactContact>;
    /**
     * email of user who created the document
     * @type {string}
     * @memberof LegacyDocumentDocument
     */
    createdBy?: string;
    /**
     * date of creation of the document
     * @type {string}
     * @memberof LegacyDocumentDocument
     */
    createdOn?: string;
    /**
     * email of user who last modified the document
     * @type {string}
     * @memberof LegacyDocumentDocument
     */
    modifiedBy?: string;
    /**
     * date of the last modification of the document
     * @type {string}
     * @memberof LegacyDocumentDocument
     */
    modifiedOn?: string;
    /**
     * external key of the document
     * @type {string}
     * @memberof LegacyDocumentDocument
     */
    externalKey?: string;
    /**
     * date start of the document
     * @type {string}
     * @memberof LegacyDocumentDocument
     */
    dateStart?: string;
    /**
     * date end of the document
     * @type {string}
     * @memberof LegacyDocumentDocument
     */
    dateEnd?: string;
    /**
     * date signature of the document
     * @type {string}
     * @memberof LegacyDocumentDocument
     */
    dateSignature?: string;
    /**
     * author of the document
     * @type {string}
     * @memberof LegacyDocumentDocument
     */
    writtenBy?: string;
    /**
     * notes of the document
     * @type {string}
     * @memberof LegacyDocumentDocument
     */
    notes?: string;
    /**
     * users related to the document
     * @type {Array<LegacyUser>}
     * @memberof LegacyDocumentDocument
     */
    users?: Array<LegacyUser>;
    /**
     * id of the document
     * @type {string}
     * @memberof LegacyDocumentDocument
     */
    id?: string;
    /**
     * type of the document
     * @type {string}
     * @memberof LegacyDocumentDocument
     */
    type?: string;
    /**
     * subtype of the document
     * @type {string}
     * @memberof LegacyDocumentDocument
     */
    subType?: string;
    /**
     * name of the document
     * @type {string}
     * @memberof LegacyDocumentDocument
     */
    name?: string;
}

export function LegacyDocumentDocumentFromJSON(json: any): LegacyDocumentDocument {
    return LegacyDocumentDocumentFromJSONTyped(json, false);
}

export function LegacyDocumentDocumentFromJSONTyped(json: any, _ignoreDiscriminator: boolean): LegacyDocumentDocument {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'files': !exists(json, 'files') ? undefined : ((json['files'] as Array<any>).map(LegacyDocumentFileFromJSON)),
        'contacts': !exists(json, 'contacts') ? undefined : ((json['contacts'] as Array<any>).map(LegacyContactContactFromJSON)),
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'createdOn': !exists(json, 'createdOn') ? undefined : json['createdOn'],
        'modifiedBy': !exists(json, 'modifiedBy') ? undefined : json['modifiedBy'],
        'modifiedOn': !exists(json, 'modifiedOn') ? undefined : json['modifiedOn'],
        'externalKey': !exists(json, 'externalKey') ? undefined : json['externalKey'],
        'dateStart': !exists(json, 'dateStart') ? undefined : json['dateStart'],
        'dateEnd': !exists(json, 'dateEnd') ? undefined : json['dateEnd'],
        'dateSignature': !exists(json, 'dateSignature') ? undefined : json['dateSignature'],
        'writtenBy': !exists(json, 'writtenBy') ? undefined : json['writtenBy'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'users': !exists(json, 'users') ? undefined : ((json['users'] as Array<any>).map(LegacyUserFromJSON)),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'subType': !exists(json, 'subType') ? undefined : json['subType'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function LegacyDocumentDocumentToJSON(value?: LegacyDocumentDocument | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'files': value.files === undefined ? undefined : ((value.files as Array<any>).map(LegacyDocumentFileToJSON)),
        'contacts': value.contacts === undefined ? undefined : ((value.contacts as Array<any>).map(LegacyContactContactToJSON)),
        'createdBy': value.createdBy,
        'createdOn': value.createdOn,
        'modifiedBy': value.modifiedBy,
        'modifiedOn': value.modifiedOn,
        'externalKey': value.externalKey,
        'dateStart': value.dateStart,
        'dateEnd': value.dateEnd,
        'dateSignature': value.dateSignature,
        'writtenBy': value.writtenBy,
        'notes': value.notes,
        'users': value.users === undefined ? undefined : ((value.users as Array<any>).map(LegacyUserToJSON)),
        'id': value.id,
        'type': value.type,
        'subType': value.subType,
        'name': value.name,
    };
}


