/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LegacyAddUpdateItem
 */
export interface LegacyAddUpdateItem {
    /**
     * id of the added item
     * @type {string}
     * @memberof LegacyAddUpdateItem
     */
    id?: string;
    /**
     * External key assigned to the item
     * @type {string}
     * @memberof LegacyAddUpdateItem
     */
    externalKey?: string;
    /**
     * Status of the Add or Update command ("inserted" | "updated")
     * @type {string}
     * @memberof LegacyAddUpdateItem
     */
    result?: string;
}

export function LegacyAddUpdateItemFromJSON(json: any): LegacyAddUpdateItem {
    return LegacyAddUpdateItemFromJSONTyped(json, false);
}

export function LegacyAddUpdateItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegacyAddUpdateItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'externalKey': !exists(json, 'externalKey') ? undefined : json['externalKey'],
        'result': !exists(json, 'result') ? undefined : json['result'],
    };
}

export function LegacyAddUpdateItemToJSON(value?: LegacyAddUpdateItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'externalKey': value.externalKey,
        'result': value.result,
    };
}


