/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    LegacyDocumentDocument,
} from './';

/**
 * 
 * @export
 * @interface LegacyDocumentGetResponseAllOf
 */
export interface LegacyDocumentGetResponseAllOf {
    /**
     * Array of documents
     * @type {Array<LegacyDocumentDocument>}
     * @memberof LegacyDocumentGetResponseAllOf
     */
    documents: Array<LegacyDocumentDocument>;
}

export function LegacyDocumentGetResponseAllOfFromJSON(json: any): LegacyDocumentGetResponseAllOf {
    return LegacyDocumentGetResponseAllOfFromJSONTyped(json, false);
}

export function LegacyDocumentGetResponseAllOfFromJSONTyped(json: any, _ignoreDiscriminator: boolean): LegacyDocumentGetResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documents': Array&lt;LegacyDocumentDocument&gt;FromJSON(json['documents']),
    };
}

export function LegacyDocumentGetResponseAllOfToJSON(value?: LegacyDocumentGetResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'documents': Array&lt;LegacyDocumentDocument&gt;ToJSON(value.documents),
    };
}


