/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LegacyDocumentBase64FilePayloadItem,
    LegacyDocumentBase64FilePayloadItemFromJSON,
    LegacyDocumentBase64FilePayloadItemFromJSONTyped,
    LegacyDocumentBase64FilePayloadItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface LegacyDocumentBase64FilePayload
 */
export interface LegacyDocumentBase64FilePayload {
    /**
     * 
     * @type {Array<LegacyDocumentBase64FilePayloadItem>}
     * @memberof LegacyDocumentBase64FilePayload
     */
    files?: Array<LegacyDocumentBase64FilePayloadItem>;
}

export function LegacyDocumentBase64FilePayloadFromJSON(json: any): LegacyDocumentBase64FilePayload {
    return LegacyDocumentBase64FilePayloadFromJSONTyped(json, false);
}

export function LegacyDocumentBase64FilePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegacyDocumentBase64FilePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'files': !exists(json, 'files') ? undefined : ((json['files'] as Array<any>).map(LegacyDocumentBase64FilePayloadItemFromJSON)),
    };
}

export function LegacyDocumentBase64FilePayloadToJSON(value?: LegacyDocumentBase64FilePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'files': value.files === undefined ? undefined : ((value.files as Array<any>).map(LegacyDocumentBase64FilePayloadItemToJSON)),
    };
}


