/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LegacyUser
 */
export interface LegacyUser {
    /**
     * id of the user
     * @type {string}
     * @memberof LegacyUser
     */
    id?: string;
    /**
     * display name of the user
     * @type {string}
     * @memberof LegacyUser
     */
    displayName?: string;
    /**
     * email of the user
     * @type {string}
     * @memberof LegacyUser
     */
    email?: string;
}

export function LegacyUserFromJSON(json: any): LegacyUser {
    return LegacyUserFromJSONTyped(json, false);
}

export function LegacyUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegacyUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function LegacyUserToJSON(value?: LegacyUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'displayName': value.displayName,
        'email': value.email,
    };
}


