/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    LegacyProvisioningOrganizationItem,
    LegacyProvisioningOrganizationItemFromJSON,
    LegacyProvisioningOrganizationItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface LegacyProvisioningGetOrganizationResponse
 */
export interface LegacyProvisioningGetOrganizationResponse {
    /**
     * Status of the request that has been made. Can be 'ok' or 'fail'
     * @type {string}
     * @memberof LegacyProvisioningGetOrganizationResponse
     */
    stat?: string;
    /**
     * If the request has failed, this element will contain the error code related to the problem encountered.
     * @type {string}
     * @memberof LegacyProvisioningGetOrganizationResponse
     */
    errorCode?: string;
    /**
     * If the request has failed, this element will contain the error message related to the problem encountered.
     * @type {string}
     * @memberof LegacyProvisioningGetOrganizationResponse
     */
    errorMsg?: string;
    /**
     * 
     * @type {LegacyProvisioningOrganizationItem}
     * @memberof LegacyProvisioningGetOrganizationResponse
     */
    organization: LegacyProvisioningOrganizationItem;
}

export function LegacyProvisioningGetOrganizationResponseFromJSON(json: any): LegacyProvisioningGetOrganizationResponse {
    return LegacyProvisioningGetOrganizationResponseFromJSONTyped(json, false);
}

export function LegacyProvisioningGetOrganizationResponseFromJSONTyped(json: any, _ignoreDiscriminator: boolean): LegacyProvisioningGetOrganizationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stat': !exists(json, 'stat') ? undefined : json['stat'],
        'errorCode': !exists(json, 'error_code') ? undefined : json['error_code'],
        'errorMsg': !exists(json, 'error_msg') ? undefined : json['error_msg'],
        'organization': LegacyProvisioningOrganizationItemFromJSON(json['organization']),
    };
}

export function LegacyProvisioningGetOrganizationResponseToJSON(value?: LegacyProvisioningGetOrganizationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stat': value.stat,
        'error_code': value.errorCode,
        'error_msg': value.errorMsg,
        'organization': LegacyProvisioningOrganizationItemToJSON(value.organization),
    };
}


