/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface LegacyDocumentBase64FilePayloadItemAllOf
 */
export interface LegacyDocumentBase64FilePayloadItemAllOf {
    /**
     * The file external key
     * @type {string}
     * @memberof LegacyDocumentBase64FilePayloadItemAllOf
     */
    externalKey?: string;
    /**
     * file data encoded in base 64
     * @type {string}
     * @memberof LegacyDocumentBase64FilePayloadItemAllOf
     */
    base64EncodedData?: string;
}

export function LegacyDocumentBase64FilePayloadItemAllOfFromJSON(json: any): LegacyDocumentBase64FilePayloadItemAllOf {
    return LegacyDocumentBase64FilePayloadItemAllOfFromJSONTyped(json, false);
}

export function LegacyDocumentBase64FilePayloadItemAllOfFromJSONTyped(json: any, _ignoreDiscriminator: boolean): LegacyDocumentBase64FilePayloadItemAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'externalKey': !exists(json, 'externalKey') ? undefined : json['externalKey'],
        'base64EncodedData': !exists(json, 'base64EncodedData') ? undefined : json['base64EncodedData'],
    };
}

export function LegacyDocumentBase64FilePayloadItemAllOfToJSON(value?: LegacyDocumentBase64FilePayloadItemAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'externalKey': value.externalKey,
        'base64EncodedData': value.base64EncodedData,
    };
}


