/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    LegacyAddUpdateItem,
} from './';

/**
 * 
 * @export
 * @interface LegacyAddUpdateResponseAllOf
 */
export interface LegacyAddUpdateResponseAllOf {
    /**
     * List all items status for the Add or Update operation
     * @type {Array<LegacyAddUpdateItem>}
     * @memberof LegacyAddUpdateResponseAllOf
     */
    items: Array<LegacyAddUpdateItem>;
}

export function LegacyAddUpdateResponseAllOfFromJSON(json: any): LegacyAddUpdateResponseAllOf {
    return LegacyAddUpdateResponseAllOfFromJSONTyped(json, false);
}

export function LegacyAddUpdateResponseAllOfFromJSONTyped(json: any, _ignoreDiscriminator: boolean): LegacyAddUpdateResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': Array&lt;LegacyAddUpdateItem&gt;FromJSON(json['items']),
    };
}

export function LegacyAddUpdateResponseAllOfToJSON(value?: LegacyAddUpdateResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': Array&lt;LegacyAddUpdateItem&gt;ToJSON(value.items),
    };
}


