/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    MovementDatabase,
    MovementDatabaseFromJSON,
    MovementDatabaseToJSON,
    MovementUser,
    MovementUserFromJSON,
    MovementUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface MovementClientBaseUsingFileMovementAllOf
 */
export interface MovementClientBaseUsingFileMovementAllOf {
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementAllOf
     */
    type: MovementClientBaseUsingFileMovementAllOfTypeEnum;
    /**
     * 
     * @type {MovementDatabase}
     * @memberof MovementClientBaseUsingFileMovementAllOf
     */
    sourceDatabase: MovementDatabase;
    /**
     * 
     * @type {MovementUser}
     * @memberof MovementClientBaseUsingFileMovementAllOf
     */
    sourceUser: MovementUser;
    /**
     * 
     * @type {MovementDatabase}
     * @memberof MovementClientBaseUsingFileMovementAllOf
     */
    destinationDatabase: MovementDatabase;
    /**
     * 
     * @type {MovementUser}
     * @memberof MovementClientBaseUsingFileMovementAllOf
     */
    destinationUser: MovementUser;
    /**
     * 
     * @type {boolean}
     * @memberof MovementClientBaseUsingFileMovementAllOf
     */
    capsil?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MovementClientBaseUsingFileMovementAllOf
     */
    univeris?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MovementClientBaseUsingFileMovementAllOf
     */
    dataphile?: boolean;
}

export function MovementClientBaseUsingFileMovementAllOfFromJSON(json: any): MovementClientBaseUsingFileMovementAllOf {
    return MovementClientBaseUsingFileMovementAllOfFromJSONTyped(json, false);
}

export function MovementClientBaseUsingFileMovementAllOfFromJSONTyped(json: any, _ignoreDiscriminator: boolean): MovementClientBaseUsingFileMovementAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'sourceDatabase': MovementDatabaseFromJSON(json['sourceDatabase']),
        'sourceUser': MovementUserFromJSON(json['sourceUser']),
        'destinationDatabase': MovementDatabaseFromJSON(json['destinationDatabase']),
        'destinationUser': MovementUserFromJSON(json['destinationUser']),
        'capsil': !exists(json, 'capsil') ? undefined : json['capsil'],
        'univeris': !exists(json, 'univeris') ? undefined : json['univeris'],
        'dataphile': !exists(json, 'dataphile') ? undefined : json['dataphile'],
    };
}

export function MovementClientBaseUsingFileMovementAllOfToJSON(value?: MovementClientBaseUsingFileMovementAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'sourceDatabase': MovementDatabaseToJSON(value.sourceDatabase),
        'sourceUser': MovementUserToJSON(value.sourceUser),
        'destinationDatabase': MovementDatabaseToJSON(value.destinationDatabase),
        'destinationUser': MovementUserToJSON(value.destinationUser),
        'capsil': value.capsil,
        'univeris': value.univeris,
        'dataphile': value.dataphile,
    };
}

/**
* @export
* @enum {string}
*/
export enum MovementClientBaseUsingFileMovementAllOfTypeEnum {
    CLIENTBASE_USING_FILE = 'CLIENTBASE_USING_FILE'
}


