/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MovementDatabase,
    MovementDatabaseFromJSON,
    MovementDatabaseToJSON,
    MovementMovement,
    MovementMovementFromJSONTyped,
    MovementMovementToJSON,
    MovementUserTuple,
} from './';

/**
 * 
 * @export
 * @interface MovementCopyMovement
 */
export interface MovementCopyMovement extends MovementMovement {
    /**
     * 
     * @type {string}
     * @memberof MovementCopyMovement
     */
    type: MovementCopyMovementTypeEnum;
    /**
     * 
     * @type {MovementDatabase}
     * @memberof MovementCopyMovement
     */
    sourceDatabase: MovementDatabase;
    /**
     * 
     * @type {MovementDatabase}
     * @memberof MovementCopyMovement
     */
    destinationDatabase: MovementDatabase;
    /**
     * 
     * @type {Array<MovementUserTuple>}
     * @memberof MovementCopyMovement
     */
    userTuples: Array<MovementUserTuple>;
}

export function MovementCopyMovementFromJSON(json: any): MovementCopyMovement {
    return MovementCopyMovementFromJSONTyped(json, false);
}

export function MovementCopyMovementFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovementCopyMovement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...MovementMovementFromJSONTyped(json, ignoreDiscriminator),
        'type': json['type'],
        'sourceDatabase': MovementDatabaseFromJSON(json['sourceDatabase']),
        'destinationDatabase': MovementDatabaseFromJSON(json['destinationDatabase']),
        'userTuples': Array&lt;MovementUserTuple&gt;FromJSON(json['userTuples']),
    };
}

export function MovementCopyMovementToJSON(value?: MovementCopyMovement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...MovementMovementToJSON(value),
        'type': value.type,
        'sourceDatabase': MovementDatabaseToJSON(value.sourceDatabase),
        'destinationDatabase': MovementDatabaseToJSON(value.destinationDatabase),
        'userTuples': Array&lt;MovementUserTuple&gt;ToJSON(value.userTuples),
    };
}

/**
* @export
* @enum {string}
*/
export enum MovementCopyMovementTypeEnum {
    COPY = 'COPY'
}


