/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MovementDatabase,
    MovementDatabaseFromJSON,
    MovementDatabaseToJSON,
    MovementGatewayAccessCode,
    MovementGatewayAccessCodeFromJSON,
    MovementGatewayAccessCodeToJSON,
    MovementMovement,
    MovementMovementFromJSONTyped,
    MovementMovementToJSON,
    MovementUser,
    MovementUserFromJSON,
    MovementUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface MovementReassignmentMovement
 */
export interface MovementReassignmentMovement extends MovementMovement {
    /**
     * 
     * @type {string}
     * @memberof MovementReassignmentMovement
     */
    type: MovementReassignmentMovementTypeEnum;
    /**
     * 
     * @type {MovementDatabase}
     * @memberof MovementReassignmentMovement
     */
    sourceDatabase: MovementDatabase;
    /**
     * 
     * @type {MovementUser}
     * @memberof MovementReassignmentMovement
     */
    sourceUser: MovementUser;
    /**
     * 
     * @type {MovementUser}
     * @memberof MovementReassignmentMovement
     */
    destinationUser: MovementUser;
    /**
     * 
     * @type {MovementGatewayAccessCode}
     * @memberof MovementReassignmentMovement
     */
    accessCode: MovementGatewayAccessCode;
}

export function MovementReassignmentMovementFromJSON(json: any): MovementReassignmentMovement {
    return MovementReassignmentMovementFromJSONTyped(json, false);
}

export function MovementReassignmentMovementFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovementReassignmentMovement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...MovementMovementFromJSONTyped(json, ignoreDiscriminator),
        'type': json['type'],
        'sourceDatabase': MovementDatabaseFromJSON(json['sourceDatabase']),
        'sourceUser': MovementUserFromJSON(json['sourceUser']),
        'destinationUser': MovementUserFromJSON(json['destinationUser']),
        'accessCode': MovementGatewayAccessCodeFromJSON(json['accessCode']),
    };
}

export function MovementReassignmentMovementToJSON(value?: MovementReassignmentMovement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...MovementMovementToJSON(value),
        'type': value.type,
        'sourceDatabase': MovementDatabaseToJSON(value.sourceDatabase),
        'sourceUser': MovementUserToJSON(value.sourceUser),
        'destinationUser': MovementUserToJSON(value.destinationUser),
        'accessCode': MovementGatewayAccessCodeToJSON(value.accessCode),
    };
}

/**
* @export
* @enum {string}
*/
export enum MovementReassignmentMovementTypeEnum {
    REASSIGNMENT = 'REASSIGNMENT'
}


