/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum MovementMovementStatus {
    TODO = 'TODO',
    CANCELLED = 'CANCELLED',
    IGNORED = 'IGNORED',
    FAILURE = 'FAILURE',
    SUCCESS = 'SUCCESS'
}

export function MovementMovementStatusFromJSON(json: any): MovementMovementStatus {
    return MovementMovementStatusFromJSONTyped(json, false);
}

export function MovementMovementStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovementMovementStatus {
    return json as MovementMovementStatus;
}

export function MovementMovementStatusToJSON(value?: MovementMovementStatus | null): any {
    return value as any;
}

