/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    MovementValidationError,
} from './';

/**
 * 
 * @export
 * @interface MovementValidationErrorResponse
 */
export interface MovementValidationErrorResponse {
    /**
     * 
     * @type {{ [key: string]: MovementValidationError; }}
     * @memberof MovementValidationErrorResponse
     */
    errors?: { [key: string]: MovementValidationError; };
}

export function MovementValidationErrorResponseFromJSON(json: any): MovementValidationErrorResponse {
    return MovementValidationErrorResponseFromJSONTyped(json, false);
}

export function MovementValidationErrorResponseFromJSONTyped(json: any, _ignoreDiscriminator: boolean): MovementValidationErrorResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': !exists(json, 'errors') ? undefined : { [key: string]: MovementValidationError; }FromJSON(json['errors']),
    };
}

export function MovementValidationErrorResponseToJSON(value?: MovementValidationErrorResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': { [key: string]: MovementValidationError; }ToJSON(value.errors),
    };
}


