/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovementMoveMovementPayloadAllOf
 */
export interface MovementMoveMovementPayloadAllOf {
    /**
     * 
     * @type {string}
     * @memberof MovementMoveMovementPayloadAllOf
     */
    type: MovementMoveMovementPayloadAllOfTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MovementMoveMovementPayloadAllOf
     */
    sourceDatabase: string;
    /**
     * 
     * @type {string}
     * @memberof MovementMoveMovementPayloadAllOf
     */
    destinationDatabase: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MovementMoveMovementPayloadAllOf
     */
    users: Array<string>;
}

export function MovementMoveMovementPayloadAllOfFromJSON(json: any): MovementMoveMovementPayloadAllOf {
    return MovementMoveMovementPayloadAllOfFromJSONTyped(json, false);
}

export function MovementMoveMovementPayloadAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovementMoveMovementPayloadAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'sourceDatabase': json['sourceDatabase'],
        'destinationDatabase': json['destinationDatabase'],
        'users': json['users'],
    };
}

export function MovementMoveMovementPayloadAllOfToJSON(value?: MovementMoveMovementPayloadAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'sourceDatabase': value.sourceDatabase,
        'destinationDatabase': value.destinationDatabase,
        'users': value.users,
    };
}

/**
* @export
* @enum {string}
*/
export enum MovementMoveMovementPayloadAllOfTypeEnum {
    MOVE = 'MOVE'
}


