/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    MovementMovementPayload,
    MovementMovementPayloadFromJSONTyped,
    MovementMovementPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface MovementClientBaseUsingFileMovementPayload
 */
export interface MovementClientBaseUsingFileMovementPayload extends MovementMovementPayload {
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayload
     */
    type: MovementClientBaseUsingFileMovementPayloadTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayload
     */
    sourceDatabase: string;
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayload
     */
    sourceUser: string;
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayload
     */
    destinationDatabase: string;
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayload
     */
    destinationUser: string;
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayload
     */
    capsilFile?: string;
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayload
     */
    univerisFile?: string;
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayload
     */
    dataphileFile?: string;
}

export function MovementClientBaseUsingFileMovementPayloadFromJSON(json: any): MovementClientBaseUsingFileMovementPayload {
    return MovementClientBaseUsingFileMovementPayloadFromJSONTyped(json, false);
}

export function MovementClientBaseUsingFileMovementPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovementClientBaseUsingFileMovementPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...MovementMovementPayloadFromJSONTyped(json, ignoreDiscriminator),
        'type': json['type'],
        'sourceDatabase': json['sourceDatabase'],
        'sourceUser': json['sourceUser'],
        'destinationDatabase': json['destinationDatabase'],
        'destinationUser': json['destinationUser'],
        'capsilFile': !exists(json, 'capsilFile') ? undefined : json['capsilFile'],
        'univerisFile': !exists(json, 'univerisFile') ? undefined : json['univerisFile'],
        'dataphileFile': !exists(json, 'dataphileFile') ? undefined : json['dataphileFile'],
    };
}

export function MovementClientBaseUsingFileMovementPayloadToJSON(value?: MovementClientBaseUsingFileMovementPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...MovementMovementPayloadToJSON(value),
        'type': value.type,
        'sourceDatabase': value.sourceDatabase,
        'sourceUser': value.sourceUser,
        'destinationDatabase': value.destinationDatabase,
        'destinationUser': value.destinationUser,
        'capsilFile': value.capsilFile,
        'univerisFile': value.univerisFile,
        'dataphileFile': value.dataphileFile,
    };
}

/**
* @export
* @enum {string}
*/
export enum MovementClientBaseUsingFileMovementPayloadTypeEnum {
    CLIENTBASE_USING_FILE = 'CLIENTBASE_USING_FILE'
}


