/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum MovementTransferOption {
    COPY = 'COPY',
    TRANSFER = 'TRANSFER'
}

export function MovementTransferOptionFromJSON(json: any): MovementTransferOption {
    return MovementTransferOptionFromJSONTyped(json, false);
}

export function MovementTransferOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovementTransferOption {
    return json as MovementTransferOption;
}

export function MovementTransferOptionToJSON(value?: MovementTransferOption | null): any {
    return value as any;
}

