/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MovementUser,
    MovementUserFromJSON,
    MovementUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface MovementUserTuple
 */
export interface MovementUserTuple {
    /**
     * 
     * @type {MovementUser}
     * @memberof MovementUserTuple
     */
    from: MovementUser;
    /**
     * 
     * @type {MovementUser}
     * @memberof MovementUserTuple
     */
    to: MovementUser;
}

export function MovementUserTupleFromJSON(json: any): MovementUserTuple {
    return MovementUserTupleFromJSONTyped(json, false);
}

export function MovementUserTupleFromJSONTyped(json: any, _ignoreDiscriminator: boolean): MovementUserTuple {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': MovementUserFromJSON(json['from']),
        'to': MovementUserFromJSON(json['to']),
    };
}

export function MovementUserTupleToJSON(value?: MovementUserTuple | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': MovementUserToJSON(value.from),
        'to': MovementUserToJSON(value.to),
    };
}


