/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MovementMovement,
    MovementMovementFromJSON,
    MovementMovementToJSON,
} from './';

/**
 * 
 * @export
 * @interface MovementListMovementResponse
 */
export interface MovementListMovementResponse {
    /**
     * 
     * @type {Array<MovementMovement>}
     * @memberof MovementListMovementResponse
     */
    items: Array<MovementMovement>;
}

export function MovementListMovementResponseFromJSON(json: any): MovementListMovementResponse {
    return MovementListMovementResponseFromJSONTyped(json, false);
}

export function MovementListMovementResponseFromJSONTyped(json: any, _ignoreDiscriminator: boolean): MovementListMovementResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(MovementMovementFromJSON)),
    };
}

export function MovementListMovementResponseToJSON(value?: MovementListMovementResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(MovementMovementToJSON)),
    };
}


