/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface MovementClientBaseUsingFileMovementPayloadAllOf
 */
export interface MovementClientBaseUsingFileMovementPayloadAllOf {
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayloadAllOf
     */
    type: MovementClientBaseUsingFileMovementPayloadAllOfTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayloadAllOf
     */
    sourceDatabase: string;
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayloadAllOf
     */
    sourceUser: string;
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayloadAllOf
     */
    destinationDatabase: string;
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayloadAllOf
     */
    destinationUser: string;
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayloadAllOf
     */
    capsilFile?: string;
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayloadAllOf
     */
    univerisFile?: string;
    /**
     * 
     * @type {string}
     * @memberof MovementClientBaseUsingFileMovementPayloadAllOf
     */
    dataphileFile?: string;
}

export function MovementClientBaseUsingFileMovementPayloadAllOfFromJSON(json: any): MovementClientBaseUsingFileMovementPayloadAllOf {
    return MovementClientBaseUsingFileMovementPayloadAllOfFromJSONTyped(json, false);
}

export function MovementClientBaseUsingFileMovementPayloadAllOfFromJSONTyped(json: any, _ignoreDiscriminator: boolean): MovementClientBaseUsingFileMovementPayloadAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'sourceDatabase': json['sourceDatabase'],
        'sourceUser': json['sourceUser'],
        'destinationDatabase': json['destinationDatabase'],
        'destinationUser': json['destinationUser'],
        'capsilFile': !exists(json, 'capsilFile') ? undefined : json['capsilFile'],
        'univerisFile': !exists(json, 'univerisFile') ? undefined : json['univerisFile'],
        'dataphileFile': !exists(json, 'dataphileFile') ? undefined : json['dataphileFile'],
    };
}

export function MovementClientBaseUsingFileMovementPayloadAllOfToJSON(value?: MovementClientBaseUsingFileMovementPayloadAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'sourceDatabase': value.sourceDatabase,
        'sourceUser': value.sourceUser,
        'destinationDatabase': value.destinationDatabase,
        'destinationUser': value.destinationUser,
        'capsilFile': value.capsilFile,
        'univerisFile': value.univerisFile,
        'dataphileFile': value.dataphileFile,
    };
}

/**
* @export
* @enum {string}
*/
export enum MovementClientBaseUsingFileMovementPayloadAllOfTypeEnum {
    CLIENTBASE_USING_FILE = 'CLIENTBASE_USING_FILE'
}


