/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovementDatabase
 */
export interface MovementDatabase {
    /**
     * 
     * @type {string}
     * @memberof MovementDatabase
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MovementDatabase
     */
    displayName?: string;
}

export function MovementDatabaseFromJSON(json: any): MovementDatabase {
    return MovementDatabaseFromJSONTyped(json, false);
}

export function MovementDatabaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovementDatabase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
    };
}

export function MovementDatabaseToJSON(value?: MovementDatabase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'displayName': value.displayName,
    };
}


