/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    MovementMovementPayload,
    MovementMovementPayloadFromJSONTyped,
    MovementMovementPayloadToJSON,
    MovementUserTuplePayload,
    MovementUserTuplePayloadFromJSON,
    MovementUserTuplePayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface MovementCopyMovementPayload
 */
export interface MovementCopyMovementPayload extends MovementMovementPayload {
    /**
     * 
     * @type {string}
     * @memberof MovementCopyMovementPayload
     */
    type: MovementCopyMovementPayloadTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MovementCopyMovementPayload
     */
    sourceDatabase: string;
    /**
     * 
     * @type {string}
     * @memberof MovementCopyMovementPayload
     */
    destinationDatabase: string;
    /**
     * 
     * @type {Array<MovementUserTuplePayload>}
     * @memberof MovementCopyMovementPayload
     */
    userTuples?: Array<MovementUserTuplePayload>;
}

export function MovementCopyMovementPayloadFromJSON(json: any): MovementCopyMovementPayload {
    return MovementCopyMovementPayloadFromJSONTyped(json, false);
}

export function MovementCopyMovementPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovementCopyMovementPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...MovementMovementPayloadFromJSONTyped(json, ignoreDiscriminator),
        'type': json['type'],
        'sourceDatabase': json['sourceDatabase'],
        'destinationDatabase': json['destinationDatabase'],
        'userTuples': !exists(json, 'userTuples') ? undefined : ((json['userTuples'] as Array<any>).map(MovementUserTuplePayloadFromJSON)),
    };
}

export function MovementCopyMovementPayloadToJSON(value?: MovementCopyMovementPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...MovementMovementPayloadToJSON(value),
        'type': value.type,
        'sourceDatabase': value.sourceDatabase,
        'destinationDatabase': value.destinationDatabase,
        'userTuples': value.userTuples === undefined ? undefined : ((value.userTuples as Array<any>).map(MovementUserTuplePayloadToJSON)),
    };
}

/**
* @export
* @enum {string}
*/
export enum MovementCopyMovementPayloadTypeEnum {
    COPY = 'COPY'
}


