/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovementValidationError
 */
export interface MovementValidationError {
    /**
     * 
     * @type {string}
     * @memberof MovementValidationError
     */
    message?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MovementValidationError
     */
    context?: { [key: string]: string; };
}

export function MovementValidationErrorFromJSON(json: any): MovementValidationError {
    return MovementValidationErrorFromJSONTyped(json, false);
}

export function MovementValidationErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovementValidationError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'context': !exists(json, 'context') ? undefined : json['context'],
    };
}

export function MovementValidationErrorToJSON(value?: MovementValidationError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'context': value.context,
    };
}


