/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    MovementUserTuplePayload,
    MovementUserTuplePayloadFromJSON,
    MovementUserTuplePayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface MovementCopyMovementPayloadAllOf
 */
export interface MovementCopyMovementPayloadAllOf {
    /**
     * 
     * @type {string}
     * @memberof MovementCopyMovementPayloadAllOf
     */
    type: MovementCopyMovementPayloadAllOfTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MovementCopyMovementPayloadAllOf
     */
    sourceDatabase: string;
    /**
     * 
     * @type {string}
     * @memberof MovementCopyMovementPayloadAllOf
     */
    destinationDatabase: string;
    /**
     * 
     * @type {Array<MovementUserTuplePayload>}
     * @memberof MovementCopyMovementPayloadAllOf
     */
    userTuples?: Array<MovementUserTuplePayload>;
}

export function MovementCopyMovementPayloadAllOfFromJSON(json: any): MovementCopyMovementPayloadAllOf {
    return MovementCopyMovementPayloadAllOfFromJSONTyped(json, false);
}

export function MovementCopyMovementPayloadAllOfFromJSONTyped(json: any, _ignoreDiscriminator: boolean): MovementCopyMovementPayloadAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'sourceDatabase': json['sourceDatabase'],
        'destinationDatabase': json['destinationDatabase'],
        'userTuples': !exists(json, 'userTuples') ? undefined : ((json['userTuples'] as Array<any>).map(MovementUserTuplePayloadFromJSON)),
    };
}

export function MovementCopyMovementPayloadAllOfToJSON(value?: MovementCopyMovementPayloadAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'sourceDatabase': value.sourceDatabase,
        'destinationDatabase': value.destinationDatabase,
        'userTuples': value.userTuples === undefined ? undefined : ((value.userTuples as Array<any>).map(MovementUserTuplePayloadToJSON)),
    };
}

/**
* @export
* @enum {string}
*/
export enum MovementCopyMovementPayloadAllOfTypeEnum {
    COPY = 'COPY'
}


