/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovementUser
 */
export interface MovementUser {
    /**
     * 
     * @type {number}
     * @memberof MovementUser
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MovementUser
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof MovementUser
     */
    displayName?: string;
}

export function MovementUserFromJSON(json: any): MovementUser {
    return MovementUserFromJSONTyped(json, false);
}

export function MovementUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovementUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
    };
}

export function MovementUserToJSON(value?: MovementUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'uuid': value.uuid,
        'displayName': value.displayName,
    };
}


