/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MxRecipient,
} from './';

/**
 * 
 * @export
 * @interface MxValidateRecipientsResponse
 */
export interface MxValidateRecipientsResponse {
    /**
     * invalidRecipients
     * @type {Array<MxRecipient>}
     * @memberof MxValidateRecipientsResponse
     */
    invalidRecipients: Array<MxRecipient>;
}

export function MxValidateRecipientsResponseFromJSON(json: any): MxValidateRecipientsResponse {
    return MxValidateRecipientsResponseFromJSONTyped(json, false);
}

export function MxValidateRecipientsResponseFromJSONTyped(json: any, _ignoreDiscriminator: boolean): MxValidateRecipientsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'invalidRecipients': Array&lt;MxRecipient&gt;FromJSON(json['invalidRecipients']),
    };
}

export function MxValidateRecipientsResponseToJSON(value?: MxValidateRecipientsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'invalidRecipients': Array&lt;MxRecipient&gt;ToJSON(value.invalidRecipients),
    };
}


