/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TasksTask,
    TasksTaskFromJSON,
    TasksTaskFromJSONTyped,
    TasksTaskToJSON,
} from './';

/**
 * 
 * @export
 * @interface TasksListTaskResponse
 */
export interface TasksListTaskResponse {
    /**
     * Opaque token used to get the next page of the result. Omitted if no more results.
     * @type {string}
     * @memberof TasksListTaskResponse
     */
    nextPageToken?: string;
    /**
     * 
     * @type {Array<TasksTask>}
     * @memberof TasksListTaskResponse
     */
    items: Array<TasksTask>;
}

export function TasksListTaskResponseFromJSON(json: any): TasksListTaskResponse {
    return TasksListTaskResponseFromJSONTyped(json, false);
}

export function TasksListTaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksListTaskResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nextPageToken': !exists(json, 'nextPageToken') ? undefined : json['nextPageToken'],
        'items': ((json['items'] as Array<any>).map(TasksTaskFromJSON)),
    };
}

export function TasksListTaskResponseToJSON(value?: TasksListTaskResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nextPageToken': value.nextPageToken,
        'items': ((value.items as Array<any>).map(TasksTaskToJSON)),
    };
}


