/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TasksOrderByType {
    dueDate = 'dueDate',
    dueDateDesc = 'dueDateDesc',
    completedDate = 'completedDate',
    completedDateDesc = 'completedDateDesc',
    updateTime = 'updateTime',
    creationTime = 'creationTime'
}

export function TasksOrderByTypeFromJSON(json: any): TasksOrderByType {
    return TasksOrderByTypeFromJSONTyped(json, false);
}

export function TasksOrderByTypeFromJSONTyped(json: any, _ignoreDiscriminator: boolean): TasksOrderByType {
    return json as TasksOrderByType;
}

export function TasksOrderByTypeToJSON(value?: TasksOrderByType | null): any {
    return value as any;
}

