/* tslint:disable */
/* eslint-disable */
/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TasksPatchTaskResponse
 */
export interface TasksPatchTaskResponse {
    /**
     * Unique numerical identifier of the updated task.
     * @type {string}
     * @memberof TasksPatchTaskResponse
     */
    id: string;
}

export function TasksPatchTaskResponseFromJSON(json: any): TasksPatchTaskResponse {
    return TasksPatchTaskResponseFromJSONTyped(json, false);
}

export function TasksPatchTaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksPatchTaskResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function TasksPatchTaskResponseToJSON(value?: TasksPatchTaskResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


