/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface TasksCreateTaskResponse
 */
export interface TasksCreateTaskResponse {
    /**
     * Unique numerical identifier of the created task.
     * @type {string}
     * @memberof TasksCreateTaskResponse
     */
    id: string;
}

export function TasksCreateTaskResponseFromJSON(json: any): TasksCreateTaskResponse {
    return TasksCreateTaskResponseFromJSONTyped(json, false);
}

export function TasksCreateTaskResponseFromJSONTyped(json: any, _ignoreDiscriminator: boolean): TasksCreateTaskResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function TasksCreateTaskResponseToJSON(value?: TasksCreateTaskResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


