/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TasksVisibilityType {
    NORMAL = 'NORMAL',
    PRIVATE = 'PRIVATE'
}

export function TasksVisibilityTypeFromJSON(json: any): TasksVisibilityType {
    return TasksVisibilityTypeFromJSONTyped(json, false);
}

export function TasksVisibilityTypeFromJSONTyped(json: any, _ignoreDiscriminator: boolean): TasksVisibilityType {
    return json as TasksVisibilityType;
}

export function TasksVisibilityTypeToJSON(value?: TasksVisibilityType | null): any {
    return value as any;
}

