/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface TasksTransferToCompletedResponse
 */
export interface TasksTransferToCompletedResponse {
    /**
     * Unique numerical identifier of the updated event.
     * @type {string}
     * @memberof TasksTransferToCompletedResponse
     */
    id: string;
}

export function TasksTransferToCompletedResponseFromJSON(json: any): TasksTransferToCompletedResponse {
    return TasksTransferToCompletedResponseFromJSONTyped(json, false);
}

export function TasksTransferToCompletedResponseFromJSONTyped(json: any, _ignoreDiscriminator: boolean): TasksTransferToCompletedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function TasksTransferToCompletedResponseToJSON(value?: TasksTransferToCompletedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


