/**
 * Equisoft /connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface UsersUser
 */
export interface UsersUser {
    /**
     * The user's unique identifier (ID).
     * @type {number}
     * @memberof UsersUser
     */
    id?: number;
    /**
     * The user's full display name.
     * @type {string}
     * @memberof UsersUser
     */
    displayName?: string;
    /**
     * The user's eMail address.
     * @type {string}
     * @memberof UsersUser
     */
    email?: string;
    /**
     * The user's first name.
     * @type {string}
     * @memberof UsersUser
     */
    firstName?: string;
    /**
     * The user's last name.
     * @type {string}
     * @memberof UsersUser
     */
    lastName?: string;
    /**
     * The user's preferred locale.
     * @type {string}
     * @memberof UsersUser
     */
    locale?: string;
}

export function UsersUserFromJSON(json: any): UsersUser {
    return UsersUserFromJSONTyped(json, false);
}

export function UsersUserFromJSONTyped(json: any, _ignoreDiscriminator: boolean): UsersUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'locale': !exists(json, 'locale') ? undefined : json['locale'],
    };
}

export function UsersUserToJSON(value?: UsersUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'displayName': value.displayName,
        'email': value.email,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'locale': value.locale,
    };
}


